name: RunPod Icin Docker Imajini Hazirla (Docker Hub)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Docker Hub'a Giriş Yap
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker İmajını Kur ve Rafa Koy
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Burada senin Docker Hub adınla paketlenecek
          tags: ${{ secrets.DOCKER_USERNAME }}/aaa-lead-scraper:latest